version: '3.0'

services:
  app:
    image: ${DOCKER_REGISTRY}/intermittency:latest
    build:
      context: .

  timescaledb:
    image: timescaledev/timescaledb-ha:pg12-latest
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
