#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: docker-registry/influxdb-preloaded
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 8086

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

env:
  INFLUXDB_HTTP_AUTH_ENABLED: "true"
