#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: timescale/timescaledb
  # -- image tag
  tag: latest-pg14
  # -- image pull policy
  pullPolicy: Always

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 5432

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

env:
  POSTGRES_PASSWORD: password

#securityContext:
#  runAsUser: 999

controller:
  type: statefulset
volumeClaimTemplates:
  - name: data
    mountPath: /var/lib/postgresql/data
    accessMode: "ReadWriteOnce"
    size: 1Gi

resources:
  limits:
    cpu: 4000m
    memory: 3.5Gi
  requests:
    cpu: 100m
    memory: 2.7Gi
