default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  checkout_timeout: 30000
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  port: 5432
  user: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV['PGDATABASE'] %>
  schema_search_path: intermittency,public
