default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1

development:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  port: 5432
  user: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV['PGDATABASE'] %>

questdb:
  <<: *default
  database: default
  host: <%= ENV['QUESTDB_HOST'] %>
  port: 8812
  user: admin
  password: quest
  pool: 4
