default: &default
  adapter: postgresql
  encoding: unicode
  pool: 6
  checkout_timeout: 5
  #query_cache: 100

development: &development
  <<: *default
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] || 5432 %>
  user: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV['PGDATABASE'] %>
  sslmode: <%= ENV['PGSSLMODE'] %>
  schema_search_path: intermittency,public

cloud:
  <<: *development

production:
  <<: *development
  database: intermittency_prod

test:
  <<: *development
  database: intermittency_test
