default: &default
  adapter: postgresql
  encoding: unicode
  pool: 6
  checkout_timeout: 5
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] || 5432 %>
  user: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV['PGDATABASE'] %>
  sslmode: <%= ENV['PGSSLMODE'] %>
  schema_search_path: intermittency,public

development:
  <<: *default

cloud:
  <<: *default

production:
  <<: *default
  database: intermittency_prod

test:
  <<: *default
  database: intermittency_test
